### ISSUE TITLE
negative value on percentChange won't work?

### ISSUE THREAD

**Issue by jdk-sal3** [plcharriere/binance-pump-detector#2]
These setting:
percentChange = -5
timeInterval = 3600
minimumTradeCount = 500

gaves these output:
2021/10/12 15:22:42 [ZEN/USDT] PUMP DETECTED: 1.410% change in 1h0m0s (70.9 -> 71.9) [14:22:42 -> 15:22:42] with 500 trades
2021/10/12 15:30:33 [RSR/USDT] PUMP DETECTED: 1.301% change in 1h0m0s (0.03304 -> 0.03347) [14:30:33 -> 15:30:33] with 500 trades
2021/10/12 15:33:54 [RVN/USDT] PUMP DETECTED: 1.039% change in 1h0m0s (0.10487 -> 0.10596) [14:33:54 -> 15:33:54] with 500 trades
2021/10/12 15:34:35 [MBL/USDT] PUMP DETECTED: -1.497% change in 1h0m0s (0.010153 -> 0.010001) [14:34:35 -> 15:34:35] with 500 trades
2021/10/12 15:34:38 [ELF/USDT] PUMP DETECTED: -1.851% change in 1h0m0s (0.675 -> 0.6625) [14:34:38 -> 15:34:38] with 500 trades
2021/10/12 15:39:24 [STMX/USDT] PUMP DETECTED: 0.797% change in 1h0m0s (0.03134 -> 0.03159) [14:39:24 -> 15:39:24] with 500 trades
2021/10/12 15:40:52 [WAXP/USDT] PUMP DETECTED: -2.016% change in 1h0m0s (0.2827 -> 0.277) [14:40:52 -> 15:40:52] with 500 trades
2021/10/12 15:42:48 [POLY/USDT] PUMP DETECTED: -1.671% change in 1h0m0s (0.7539 -> 0.7413) [14:42:48 -> 15:42:48] with 500 trades
2021/10/12 15:43:49 [ANKR/USDT] PUMP DETECTED: 0.662% change in 1h0m0s (0.08458 -> 0.08514) [14:43:49 -> 15:43:49] with 500 trades
2021/10/12 15:46:06 [MASK/USDT] PUMP DETECTED: 2.049% change in 1h0m0s (9.171 -> 9.359) [14:46:06 -> 15:46:06] with 504 trades
2021/10/12 15:46:33 [BEAM/USDT] PUMP DETECTED: -1.784% change in 1h0m0s (0.7453 -> 0.732) [14:46:33 -> 15:46:33] with 501 trades
2021/10/12 15:47:52 [MFT/USDT] PUMP DETECTED: -2.080% change in 1h0m0s (0.012401 -> 0.012143) [14:47:52 -> 15:47:52] with 500 trades

**Comment by plcharriere** [comment]
Thanks for your issue, I'll try fix that.

**Comment by plcharriere** [comment]
I have pushed a fix, can you pull, test and tell me if it works ?

**Comment by jdk-sal3** [comment]
It works fine now...
Thanks a lot
